### PR TITLE
5.7.0 Additional (optional) rDNS/PTR AntiSpam Check

### PR DESCRIPTION
**Pull request by RvdHout**
@martinknafve
I Assume you probably would like to add some RegressionTests for this?
I can't get that to work on my dev system, so I couldn't add that...sorry!

CheckPTR

### CODE REVIEW

**Comment by RvdHout** [comment]
This closes: https://github.com/hmailserver/hmailserver/issues/176

**Comment by martinknafve** [comment]
Do you have any suggestion how this could be tested using regression tests? I don't see an obvious way, to trigger it there would be a connecting IP where the PTR record is missing or incorrect, right?

**Comment by RvdHout** [comment]
@martinknafve 

You are absolutely right there is no way to add a test for it, and to be honest no real need for it, the check returns true or false and there is little (no) room for errors, just like the MX check

**Comment by martinknafve** [comment]
Thanks. :)

**Comment by RvdHout** [comment]
@martinknafve, it think you could add a PTR check test, like this

RegressionTest -> POP3 -> Fetching -> Basics

```
      [Test]
      public void TestSpamProtectionPreTransmissionPTRFail()
      {
         _application.Settings.AntiSpam.SpamMarkThreshold = 1;
         _application.Settings.AntiSpam.SpamDeleteThreshold = 100;
         _application.Settings.AntiSpam.AddHeaderReason = true;
         _application.Settings.AntiSpam.AddHeaderSpam = true;
         _application.Settings.AntiSpam.PrependSubject = true;
         _application.Settings.AntiSpam.PrependSubjectText = "ThisIsSpam";

         _application.Settings.AntiSpam.CheckPTR = true;
         _application.Settings.AntiSpam.CheckPTRScore = 105;

         var messages = new List<string>();

         string message = "Received: from static.vnpt.vn (static.vnpt.vn [14.247.252.17]) by mail.host.edu\r\n" +
                          "From: something@static.vnpt.vn\r\n" +
                          "To: Martin@example.com\r\n" +
                          "Subject: Test\r\n" +
                          "\r\n" +
                          "Should be blocked.";

         messages.Add(message);

         int port = TestSetup.GetNextFreePort();
         using (var pop3Server = new Pop3ServerSimulator(1, port, messages))
         {
            pop3Server.StartListen();

            Account account = SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "user@test.com", "test");
            FetchAccount fa = account.FetchAccounts.Add();

            fa.Enabled = true;
            fa.MinutesBetweenFetch = 10;
            fa.Name = "Test";
            fa.Username = "test@example.com";
            fa.Password = "test";
            fa.UseSSL = false;
            fa.ServerAddress = "localhost";
            fa.Port = port;
            fa.MIMERecipientHeaders = "To,CC,X-RCPT-TO,X-Envelope-To";
            fa.ProcessMIMERecipients = false;
            fa.DaysToKeepMessages = 0;
            fa.UseAntiSpam = true;
            fa.Save();

            fa.DownloadNow();

            pop3Server.WaitForCompletion();

            fa.Delete();

            _application.Settings.AntiSpam.CheckPTR = false;

            Pop3ClientSimulator.AssertMessageCount(account.Address, "test", 0);
         }
      }

      [Test]
      public void TestSpamProtectionPreTransmissionPTRPass()
      {
         _application.Settings.AntiSpam.SpamMarkThreshold = 1;
         _application.Settings.AntiSpam.SpamDeleteThreshold = 100;
         _application.Settings.AntiSpam.AddHeaderReason = true;
         _application.Settings.AntiSpam.AddHeaderSpam = true;
         _application.Settings.AntiSpam.PrependSubject = true;
         _application.Settings.AntiSpam.PrependSubjectText = "ThisIsSpam";

         _application.Settings.AntiSpam.CheckPTR = true;
         _application.Settings.AntiSpam.CheckPTRScore = 105;

         var messages = new List<string>();

         string message = "Received: from mail-ed1-x533.google.com (mail-ed1-x533.google.com [2a00:1450:4864:20::533]) by mail.host.edu\r\n" +
                          "From: something@gmail.com\r\n" +
                          "To: Martin@example.com\r\n" +
                          "Subject: Test\r\n" +
                          "\r\n" +
                          "Should not be blocked.";

         messages.Add(message);

         int port = TestSetup.GetNextFreePort();
         using (var pop3Server = new Pop3ServerSimulator(1, port, messages))
         {
            pop3Server.StartListen();

            Account account = SingletonProvider<TestSetup>.Instance.AddAccount(_domain, "user@test.com", "test");
            FetchAccount fa = account.FetchAccounts.Add();

            fa.Enabled = true;
            fa.MinutesBetweenFetch = 10;
            fa.Name = "Test";
            fa.Username = "test@example.com";
            fa.Password = "test";
            fa.UseSSL = false;
            fa.ServerAddress = "localhost";
            fa.Port = port;
            fa.MIMERecipientHeaders = "To,CC,X-RCPT-TO,X-Envelope-To";
            fa.ProcessMIMERecipients = false;
            fa.DaysToKeepMessages = 0;
            fa.UseAntiSpam = true;
            fa.Save();

            fa.DownloadNow();

            pop3Server.WaitForCompletion();

            fa.Delete();

            _application.Settings.AntiSpam.CheckPTR = false;

            Pop3ClientSimulator.AssertMessageCount(account.Address, "test", 1);
         }
      }
```

**Pull request merged**
