### PR TITLE
5.7.0 rdns/ptr antispam option dbupdater fixes

### PR DESCRIPTION
**Pull request by RvdHout**
dbupdater fixes

### CODE REVIEW

**Comment by RvdHout** [comment]
@martinknafve 

This latest merge, does that solve the issue with the other pull request? 
FYI, the dbupdater in the latest build was missing something which made the dbupdater to fail, should be fixed, see https://github.com/hmailserver/hmailserver/issues/418

**Comment by RvdHout** [comment]
@martinknafve, i think you need [e73bd61](https://github.com/hmailserver/hmailserver/pull/419/commits/e73bd618ba5cc5496b7bef877dc4ccac7de863b1) to fix a issue with dbupdater (something i missed before)

Maybe also [5a89b95](https://github.com/hmailserver/hmailserver/pull/419/commits/5a89b9579c2c2ffd5d314f1c1a67bd3c8b8a5d15) for conflicts that this introduces?

**Comment by martinknafve** [comment]
Honestly this one is a bit of a mess. As you mentioned, it was supposed to be dbupdater fixes but the pull request contains a bunch of other commits as well. I have manually introduced the database changes now (hopefully correct) :\ I can't merge this change request now because I don't actually understand what it's supposed to contain...

**Comment by RvdHout** [comment]
I am not really sure what happened here, up to [25a74a6](https://github.com/hmailserver/hmailserver/pull/419/commits/25a74a6f9c185755d81afc2803ab90dbf257d37b) should be in previous commit, everything i committed after made a big mess, i will try to better next time ;)

**Comment by martinknafve** [comment]
No problem. Since I have manually introduced the changes I think this one can be closed now, right? I tried running and upgrade myself and it worked fine.

**Comment by RvdHout** [comment]
Yep, can be closed

**Pull request closed without merging**
