### PR TITLE
5.7.0 New ClientInfo properties

### PR DESCRIPTION
**Pull request by RvdHout**
New ClientInfo properties oClient.EncryptedConnection (Boolean), oClient.CipherVersion, oClient.CipherName and oClient.CipherBits

### CODE REVIEW

**Comment by RvdHout** [comment]
if you choose to include pull https://github.com/hmailserver/hmailserver/pull/390 make sure you also add the code below to:
 
https://github.com/RvdHout/hmailserver/commit/dadbffb4347d77ef25652f294db5c74581e05064#diff-d81c97937d1043b1c57a98802880a6139f60b0a4f45ad7d64ff95e54f233dffdR2116

and

https://github.com/RvdHout/hmailserver/commit/dadbffb4347d77ef25652f294db5c74581e05064#diff-d81c97937d1043b1c57a98802880a6139f60b0a4f45ad7d64ff95e54f233dffdR2140


```
if (IsSSLConnection())
{
	auto cipher_info = GetCipherInfo();
	pClientInfo->SetCipherVersion(cipher_info.GetVersion().c_str());
	pClientInfo->SetCipherName(cipher_info.GetName().c_str());
	pClientInfo->SetCipherBits(cipher_info.GetBits());
}
```

**Example**

```
Eventlog.Write("SSL/TLS Connection: " & oClient.EncryptedConnection)
If (oClient.EncryptedConnection) Then
	Eventlog.Write("CipherVersion: " & oClient.CipherVersion)
	Eventlog.Write("CipherName: " & oClient.CipherName)
	Eventlog.Write("CipherBits: " & oClient.CipherBits)
End If
```

**Comment by martinknafve** [comment]
Old request, but I think you should try to add some unit tests for this one. "Historically", the goal was to have all the features in hMailServer covered by unit tests. I know you had some issues running them on your computer. Can you share some info on what stopped you from running them (maybe we can get it to work)?

**Comment by RvdHout** [comment]
Basically i miss the instructions to get NUnit to work, it is not included in the readme, What version do we need NUnit 2.x or NUnit 3.x? How to install? How to run? etc

**Comment by martinknafve** [comment]
If you resolve the conflicts then I can add tests and merge it.

**Comment by RvdHout** [comment]
I gonna need some time to process through all notifications i received today....mostly my fault, involved a "few" beers 🍻😂

**Comment by martinknafve** [comment]
Haha, that's my fault for handling all these PR:s at the same time. You waited years for me so I can wait a bit.

**Comment by RvdHout** [comment]
Not sure if it is compatible with RC 1.5 or higher
https://github.com/tunis78/roundcube-hms_rules

**Comment by RvdHout** [comment]
mmm, how exactly do i fix conflicts? I though committing 'fixed' conflicting files would do, but this has to be done through "Resolve conflicts", eg: inline editor?

**Comment by RvdHout** [comment]
@martinknafve 
I might have made a mess of this.... but it says it has no more conflicts :-)

**Comment by RvdHout** [comment]
I think you forgot to include 8d47618

**Comment by RvdHout** [comment]
@martinknafve 
I think you forgot to include 8d47618

**Comment by RvdHout** [comment]
@martinknafve 
I created a new pull for the missing parts, eg: https://github.com/hmailserver/hmailserver/pull/472

**Pull request merged**
