### PR TITLE
Update SURBL.cpp

### PR DESCRIPTION
**Pull request by RvdHout**
Better URL regex for SURBL?

For more info, checkout this topic: https://www.hmailserver.com/forum/viewtopic.php?f=7&t=34743

### CODE REVIEW

**Comment by martinknafve** [comment]
It looks like this pull request contains a mix of various things now. Each individual change looks OK, but I'm not sure if they were added on purpose to this pull request?

**Comment by RvdHout** [comment]
I didn't add those on purpose to this pull request , isn't this done automatically when i commit something else to my fork?

**Comment by RvdHout** [comment]
M....i see, I think i have to:

1. Create a branch, commit & create pull request
2. Then delete that branch, and repeat step 1 for every commit i make, right?

**Comment by mstenz** [comment]
Yes, deleting a branch ist best practice.

**Comment by martinknafve** [comment]
Yes, I think you're right. I'm actually not 100% sure myself. If it's not too much work, could you try it for the SURBL change and see if that works it?

**Comment by RvdHout** [comment]
Mmmm, looks like it closes the pull request immediately after i delete the branch... doesn't seem the  proper way of doing this

**Pull request closed without merging**
