### PR TITLE
5.7.0-Cleanup

### PR DESCRIPTION
**Pull request by RvdHout**
Cleanup commented lines and change APPLICATION_LOG message(s) for consistency

### CODE REVIEW

**Comment by jimimaseye** [comment]
Im not sure your proposed grammar is correct. 

The message is being deleted by a rule at the time of the logging and therefore at time of reading it is reporting of something that HAS happened (past tense) rather than something in the future. Stating 'WILL BE' is 'future form' suggesting an event that will happen after logging (which is incorrect).  You may argue to change the tense to being current form "...is being deleted".

 However, you are mixing the tense starting "will be....was" : 

"Message *will be* deleted. Action *was* taken by..."

For me, the existing wording is adequate (no change required). If there must be a change then it could be suggested to read as present continuous:

"Message *is being* deleted. Action *is being* taken by....".

**Comment by RvdHout** [comment]
"Message will be deleted. Action is taken by....". makes more sense in that case 

This is part of these changes, https://github.com/hmailserver/hmailserver/pull/369
Deletion of message is shifted to completely the end to maintain the oMessage object

**Comment by jimimaseye** [comment]
> @jimimaseye
> 
> "Message will be deleted. Action is taken by....". makes more sense in that case

Needs to be ".. is BEING taken by..." for correct grammar. ("Is taken" is not English).

**Comment by RvdHout** [comment]
Is triggered by...

**Comment by jimimaseye** [comment]
'Triggered' is past tense. 

"Was triggered.." or.."is being triggered by..."

('Being' is English and unavoidable in everyday English of you follow the grammar rules)

**Comment by RvdHout** [comment]
You know were talking about a freaking log line, don't you?

**Comment by jimimaseye** [comment]
I do. And i can't control what you ultimately do in your chosen modifications for your version of product.  I offer the advice based on my mother tongue - you take it or leave it depending on how you care or want it to look. (It matters not to me).

**Comment by RvdHout** [comment]
Message will be deleted -> Future sense, as it still need to happen
Triggered by... past sense, as it is the reason why the message will be deleted

**Comment by RvdHout** [comment]
> It matters not to me

Is that proper grammar? 🤣

**Comment by jimimaseye** [comment]
Yes. 
(https://www.google.com/search?q=%22it+matters+not%22).

**Comment by RvdHout** [comment]
Not in my book, yours is old-fashioned and formal, how old are you exactly? ;)
It doesn't matter to me

**Comment by RvdHout** [comment]
Superseded by #427

**Comment by jimimaseye** [comment]
Indeed.  I am English mother tongue and know the language a lot more intricately. It may not be in your Dutch "book of English" but it is in the English dictionary and grammar books and to the native English language speaking world (and all English emanates from historic use and grammatical evolution thus is always 'old fashioned' to some degree.  Except "Brexit".  And yes, I just said "thus".) 😁
 Anyway, this is not the place for an English lesson....

**Comment by RvdHout** [comment]
I just committed the grammar fix, you can live with these sentences?

Message will be deleted. Action triggered by script subscribing to OnDeliveryStart.
Message will be deleted. Action triggered by script subscribing to OnDeliverMessage.
Message will be deleted. Action triggered by a global rule (Rule name: [Spam], ID: 20).

Everyone reading the log file would know what is said there, not?

**Comment by jimimaseye** [comment]
They would, yes.

**Pull request closed without merging**
